import type { NormalizedLiquidGlassOptions } from '../types/glass';

/** Defaults for the DOM-native material engine. */
export const DEFAULT_GLASS_OPTIONS: Readonly<NormalizedLiquidGlassOptions> = Object.freeze({
  blur: 0.8,
  opacity: 0.025,
  thickness: 24,
  ior: 1.5,
  refraction: 1.1,
  dispersion: 0.25,
  saturation: 1.2,
  tint: '#ffffff',
  radius: 40,
  bezel: 12,
  specular: 0.7,
  shadow: 0.3,
  shadowColor: 'rgba(255, 255, 255, 0.12)',
  surfaceShape: 'concave',
  surfaceProfile: 'concave',
  materialPreset: 'ios',
  quality: 'high',
  ambientLuma: 0.5,
  shape: 'roundedRect',
  capability: 'auto',
  fallbackPolicy: 'auto',
  debug: 'none',
  interactive: true,
  borderMode: 'adaptive',
  colorBleed: 0.15,
  refractionCoverage: 'full',
});
