import type { GlassPreset, LiquidGlassMaterialOptions } from '../types/glass';

export const GLASS_PRESETS: Readonly<Record<GlassPreset, Readonly<LiquidGlassMaterialOptions>>> =
  Object.freeze({
    'ios-like': Object.freeze({
      blur: 2.0,
      opacity: 0.06,
      thickness: 45,
      ior: 2.2,
      dispersion: 0.018,
      bezel: 38,
      specular: 0.65,
      radius: 44,
      tint: '#ffffff',
      shadow: 0.4,
    }),
    clear: Object.freeze({
      blur: 0.6,
      opacity: 0.03,
      thickness: 35,
      ior: 1.9,
      dispersion: 0.01,
      bezel: 26,
      specular: 0.88,
      radius: 36,
      tint: '#f4f8ff',
      shadow: 0.25,
    }),
    vivid: Object.freeze({
      blur: 1.8,
      opacity: 0.08,
      thickness: 60,
      ior: 2.6,
      dispersion: 0.028,
      bezel: 44,
      specular: 0.75,
      radius: 42,
      tint: '#ffffff',
      saturation: 1.6,
      shadow: 0.5,
    }),
    heavy: Object.freeze({
      blur: 6.0,
      opacity: 0.14,
      thickness: 75,
      ior: 2.8,
      dispersion: 0.022,
      bezel: 48,
      specular: 0.55,
      radius: 48,
      tint: '#1a1f2c',
      shadow: 0.6,
    }),
  });
