export type UsageCodeId = 'glass-button' | 'glass-tab-bar' | 'liquid-glass' | 'music-card';

function joinLines(lines: string[]): string {
  return lines.join('\n');
}

const glassButtonCode = joinLines([
  '<script setup lang="ts">',
  "import { shallowRef } from 'vue';",
  "import { GlassButton, type GlassButtonVariant } from '@dinqorai/liquid-glass/vue';",
  "import type { LiquidGlassMaterialOptions } from '@dinqorai/liquid-glass';",
  '',
  'const glassOptions: LiquidGlassMaterialOptions = {',
  '  blur: 0,',
  '  opacity: 0,',
  '  specular: 0.75,',
  '  shadow: 0.25,',
  '  refraction: 1,',
  "  refractionCoverage: 'full',",
  "  surfaceProfile: 'fluid_dome',",
  "  borderMode: 'adaptive',",
  "  shape: 'roundedRect',",
  "  debug: 'none',",
  '};',
  '',
  "const lastAction = shallowRef('点击按钮查看按下态');",
  '',
  'const variants: Array<{ key: GlassButtonVariant; label: string }> = [',
  "  { key: 'default', label: 'Default' },",
  "  { key: 'primary', label: 'Primary' },",
  "  { key: 'ghost', label: 'Ghost' },",
  "  { key: 'danger', label: 'Danger' },",
  '];',
  '',
  'function handleClick(label: string): void {',
  "  lastAction.value = label + ' clicked';",
  '}',
  '</script>',
  '',
  '<template>',
  '  <section class="button-preview">',
  '    <div class="button-preview-heading">',
  '      <div>',
  '        <span class="button-preview-kicker">VUE COMPONENT</span>',
  '        <h2>GlassButton</h2>',
  '      </div>',
  '      <span class="button-preview-status">{{ lastAction }}</span>',
  '    </div>',
  '',
  '    <div class="button-preview-grid">',
  '      <GlassButton',
  '        v-for="item in variants"',
  '        :key="item.key"',
  '        size="md"',
  '        :variant="item.key"',
  '        :options="glassOptions"',
  '        refraction-coverage="full"',
  '        surface-profile="fluid_dome"',
  '        border-mode="adaptive"',
  '        @click="handleClick(item.label)"',
  '      >',
  '        {{ item.label }}',
  '      </GlassButton>',
  '    </div>',
  '',
  '    <p class="button-preview-note">',
  '      md = 40px 高、圆角 20px；bezel 16px；厚度 42；按下缩放 0.97；当前预览额外使用 Full + fluid_dome。',
  '    </p>',
  '  </section>',
  '</template>',
  '',
  '<style scoped>',
  '.button-preview {',
  '  width: min(720px, 92vw);',
  '}',
  '',
  '.button-preview-heading {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  gap: 16px;',
  '  margin-bottom: 16px;',
  '}',
  '',
  '.button-preview-kicker {',
  '  color: rgba(255, 255, 255, 0.48);',
  '  font-size: 10px;',
  '  font-weight: 700;',
  '  letter-spacing: 0.14em;',
  '}',
  '',
  'h2 {',
  '  margin: 4px 0 0;',
  '  color: #fff;',
  '  font-size: 20px;',
  '}',
  '',
  '.button-preview-status {',
  '  color: rgba(255, 255, 255, 0.62);',
  '  font-size: 11px;',
  '}',
  '',
  '.button-preview-grid {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 10px;',
  '}',
  '',
  '.button-preview-note {',
  '  margin: 16px 0 0;',
  '  color: rgba(255, 255, 255, 0.58);',
  '  font-size: 11px;',
  '  line-height: 1.5;',
  '}',
  '',
  '@media (max-width: 767px) {',
  '  .button-preview {',
  '    width: 100%;',
  '    padding: 14px;',
  '    border-radius: 18px;',
  '  }',
  '',
  '  .button-preview-heading {',
  '    align-items: flex-start;',
  '    flex-wrap: wrap;',
  '    gap: 6px 12px;',
  '    margin-bottom: 12px;',
  '  }',
  '',
  '  .button-preview-status {',
  '    flex: 1 1 100%;',
  '  }',
  '',
  '  .button-preview-grid {',
  '    gap: 8px;',
  '  }',
  '',
  '  .button-preview-note {',
  '    margin-top: 12px;',
  '    font-size: 10px;',
  '  }',
  '}',
  '</style>',
]);

const glassTabBarCode = joinLines([
  '<script setup lang="ts">',
  "import { computed, shallowRef } from 'vue';",
  "import { GlassTabBar, type GlassTabBarItem } from '@dinqorai/liquid-glass/vue';",
  "import type { LiquidGlassMaterialOptions } from '@dinqorai/liquid-glass';",
  '',
  "const activeTab = shallowRef('home');",
  '',
  'const navItems = computed<GlassTabBarItem[]>(() => [',
  "  { value: 'home', label: 'Home', active: activeTab.value === 'home' },",
  "  { value: 'discover', label: 'Discover', active: activeTab.value === 'discover' },",
  "  { value: 'saved', label: 'Saved', active: activeTab.value === 'saved' },",
  "  { value: 'activity', label: 'Activity', active: activeTab.value === 'activity' },",
  "  { value: 'profile', label: 'Profile', active: activeTab.value === 'profile' },",
  ']);',
  '',
  'const navOptions = computed<LiquidGlassMaterialOptions>(() => ({',
  '  blur: 0,',
  '  opacity: 0,',
  '  specular: 0.75,',
  '  shadow: 0.25,',
  '  refraction: 1,',
  "  refractionCoverage: 'full',",
  "  shape: 'roundedRect',",
  "  debug: 'none',",
  '}));',
  '</script>',
  '',
  '<template>',
  '  <section class="clean-nav-preview" aria-label="Pure LiquidGlass navigation preview">',
  '    <div class="clean-nav-preview__caption">',
  '      <span class="clean-nav-preview__eyebrow">PURE NAV</span>',
  '      <span class="clean-nav-preview__hint">LiquidGlass base + hover lens</span>',
  '    </div>',
  '',
  '    <GlassTabBar',
      '      :items="navItems"',
  '      @click="activeTab = $event.value"',
  '      :height="76"',
  '      :item-width="88"',
  '      :radius="999"',
  '      :lens-inset="7"',
  '      responsive',
  '      :mobile-height="56"',
  '      :mobile-item-width="52"',
  '      :tablet-height="68"',
  '      :tablet-item-width="70"',
  '      :base-options="navOptions"',
  '      :lens-options="navOptions"',
  '    >',
  '      <template #item="{ item, index }">',
  '        <span class="glass-tabbar__icon clean-nav-preview__icon" aria-hidden="true">',
  '          <svg v-if="index === 0" viewBox="0 0 24 24">',
  '            <path',
  '              class="is-filled"',
  '              d="M3 10.5 12 3l9 7.5v9a1.5 1.5 0 0 1-1.5 1.5H15v-6H9v6H4.5A1.5 1.5 0 0 1 3 19.5v-9Z"',
  '            />',
  '          </svg>',
  '          <svg v-else-if="index === 1" viewBox="0 0 24 24">',
  '            <circle cx="11" cy="11" r="6.5" />',
  '            <path d="m16 16 4.5 4.5M11 7v8M7 11h8" />',
  '          </svg>',
  '          <svg v-else-if="index === 2" viewBox="0 0 24 24">',
  '            <path',
  '              class="is-filled"',
  '              d="M12 20.5 4.8 13.3a4.8 4.8 0 0 1 6.8-6.8L12 7l.4-.5a4.8 4.8 0 0 1 6.8 6.8L12 20.5Z"',
  '            />',
  '          </svg>',
  '          <svg v-else-if="index === 3" viewBox="0 0 24 24">',
  '            <path d="M4 18.5V13M10 18.5V8M16 18.5V4M22 18.5V10" />',
  '          </svg>',
  '          <svg v-else viewBox="0 0 24 24">',
  '            <circle cx="12" cy="8" r="3.5" />',
  '            <path d="M5 20a7 7 0 0 1 14 0" />',
  '          </svg>',
  '        </span>',
  '        <span class="glass-tabbar__label">{{ item.label }}</span>',
  '      </template>',
  '    </GlassTabBar>',
  '  </section>',
  '</template>',
  '',
  '<style scoped>',
  '.clean-nav-preview {',
  '  display: flex;',
  '  flex-direction: column;',
  '  align-items: center;',
  '  gap: 8px;',
  '  width: 100%;',
  '  max-width: 720px;',
  '}',
  '',
  '.clean-nav-preview__caption {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 10px;',
  '  max-width: 100%;',
  '  color: rgba(255, 255, 255, 0.56);',
  '  font-size: 10px;',
  '  line-height: 1;',
  '  white-space: nowrap;',
  '}',
  '',
  '.clean-nav-preview__eyebrow {',
  '  color: rgba(255, 255, 255, 0.74);',
  '  font-size: 10px;',
  '  font-weight: 700;',
  '  letter-spacing: 0.16em;',
  '}',
  '',
  '.clean-nav-preview__hint {',
  '  opacity: 0.72;',
  '}',
  '',
  '.clean-nav-preview__icon {',
  '  color: currentColor;',
  '}',
  '',
  '.clean-nav-preview__icon svg {',
  '  width: 21px;',
  '  height: 21px;',
  '  fill: none;',
  '  stroke: currentColor;',
  '  stroke-linecap: round;',
  '  stroke-linejoin: round;',
  '  stroke-width: 1.7;',
  '}',
  '',
  '.clean-nav-preview__icon svg .is-filled {',
  '  fill: currentColor;',
  '  stroke: none;',
  '}',
  '',
  '@media (max-width: 767px) {',
  '  .clean-nav-preview {',
  '    gap: 6px;',
  '  }',
  '',
  '  .clean-nav-preview__caption {',
  '    gap: 7px;',
  '    font-size: 9px;',
  '  }',
  '',
  '  .clean-nav-preview__eyebrow {',
  '    font-size: 9px;',
  '  }',
  '',
  '  .clean-nav-preview__icon svg {',
  '    width: 18px;',
  '    height: 18px;',
  '  }',
  '}',
  '</style>',
]);

const liquidGlassCode = joinLines([
  '<script setup lang="ts">',
  "import { LiquidGlass } from '@dinqorai/liquid-glass/vue';",
  "import type { LiquidGlassMaterialOptions } from '@dinqorai/liquid-glass';",
  '',
  'const glassOptions: LiquidGlassMaterialOptions = {',
  '  blur: 0,',
  '  opacity: 0,',
  '  specular: 0.75,',
  '  shadow: 0.25,',
  '  refraction: 1,',
  '  dispersion: 1.5,',
  '  saturation: 1.3,',
  "  refractionCoverage: 'full',",
  "  shape: 'roundedRect',",
  "  debug: 'none',",
  '};',
  '</script>',
  '',
  '<template>',
  '  <div class="single-glass-preview">',
  '    <div class="single-glass-preview__frame">',
  '      <LiquidGlass',
  '        :options="glassOptions"',
  '        :interactive="true"',
  '        style="width: 100%; height: 100%"',
  '      >',
  '        <div class="single-glass-preview__content">',
  '          <span class="single-glass-preview__icon">✦</span>',
  '          <strong>LiquidGlass</strong>',
  '          <span>hover to inspect refraction</span>',
  '        </div>',
  '      </LiquidGlass>',
  '    </div>',
  '    <p class="preview-caption">',
  '      容器本身不限制内容类型，所有视觉参数通过 options 进入同一个底层引擎。',
  '    </p>',
  '  </div>',
  '</template>',
  '',
  '<style scoped>',
  '.single-glass-preview {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: min(620px, 100%);',
  '  flex-direction: column;',
  '  gap: 18px;',
  '}',
  '',
  '.single-glass-preview__frame {',
  '  width: min(540px, 100%);',
  '  height: 250px;',
  '}',
  '',
  '.single-glass-preview__content {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: 100%;',
  '  height: 100%;',
  '  flex-direction: column;',
  '  gap: 10px;',
  '  color: rgba(255, 255, 255, 0.8);',
  '}',
  '',
  '.single-glass-preview__content strong {',
  '  color: #fff;',
  '  font-size: 24px;',
  '  letter-spacing: -0.04em;',
  '}',
  '',
  '.single-glass-preview__content span:last-child {',
  '  color: rgba(255, 255, 255, 0.5);',
  '  font-size: 11px;',
  '}',
  '',
  '.single-glass-preview__icon {',
  '  display: grid;',
  '  width: 44px;',
  '  height: 44px;',
  '  place-items: center;',
  '  border: 1px solid rgba(255, 255, 255, 0.28);',
  '  border-radius: 50%;',
  '  color: #7dd3fc;',
  '  font-size: 26px;',
  '}',
  '',
  '.preview-caption {',
  '  max-width: 520px;',
  '  margin: 0;',
  '  color: rgba(255, 255, 255, 0.48);',
  '  font-size: 11px;',
  '  line-height: 1.5;',
  '  text-align: center;',
  '}',
  '</style>',
]);

const musicCardCode = joinLines([
  '<script setup lang="ts">',
  "import { LiquidGlass } from '@dinqorai/liquid-glass/vue';",
  "import MusicPlayerCard from './MusicPlayerCard.vue';",
  '',
  'const glassOptions = {',
  '  blur: 0,',
  '  opacity: 0,',
  '  specular: 0.75,',
  '  shadow: 0.25,',
  '  refraction: 1,',
  "  refractionCoverage: 'full',",
  "  shape: 'roundedRect',",
  "  debug: 'none',",
  '};',
  '</script>',
  '',
  '<template>',
  '  <div class="music-card-preview">',
  '    <div class="music-card-preview__frame">',
  '      <LiquidGlass',
  '        :options="glassOptions"',
  '        :interactive="true"',
  '        style="width: 100%; height: 100%"',
  '      >',
  '        <MusicPlayerCard />',
  '      </LiquidGlass>',
  '    </div>',
  '    <p class="preview-caption">',
  '      内容组件保持独立，玻璃容器只负责提供材质和光学效果。',
  '    </p>',
  '  </div>',
  '</template>',
  '',
  '<style scoped>',
  '.music-card-preview {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: min(620px, 100%);',
  '  flex-direction: column;',
  '  gap: 18px;',
  '}',
  '',
  '.music-card-preview__frame {',
  '  width: min(540px, 100%);',
  '  height: 250px;',
  '}',
  '',
  '.preview-caption {',
  '  max-width: 520px;',
  '  margin: 0;',
  '  color: rgba(255, 255, 255, 0.48);',
  '  font-size: 11px;',
  '  line-height: 1.5;',
  '  text-align: center;',
  '}',
  '</style>',
]);

export const USAGE_CODE: Record<UsageCodeId, string> = {
  'glass-button': glassButtonCode,
  'glass-tab-bar': glassTabBarCode,
  'liquid-glass': liquidGlassCode,
  'music-card': musicCardCode,
};
